Fitosanidad/Controllers/Auth_FormsActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Planner.Model;
using Resources;

using System.Globalization;

using System.Data;
using System.Data.SqlClient;

namespace Fitosanidad.Controllers
{
    [Authorize]
    public class Auth_FormsActionsController : BaseController
    {
        BASEntities _BASEntities = null;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexGrid()
        {
            try
            {
                return Json(GetAllAuth_FormsActions(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Auth_FormsActions _Auth_FormsActions, FormCollection form)
        {
            try
            {
                _BASEntities = new BASEntities();
                if (ModelState.IsValid)
                {
                    Auth_FormsActions Auth_FormsActions_Add = new Auth_FormsActions();
                    Auth_FormsActions_Add.Name = _Auth_FormsActions.Name;
                    Auth_FormsActions_Add.Icon = _Auth_FormsActions.Icon;
                    Auth_FormsActions_Add.FlagActive = _Auth_FormsActions.FlagActive;

                    _BASEntities.Auth_FormsActions.Add(Auth_FormsActions_Add);
                    _BASEntities.SaveChanges();

                    return RedirectToAction("Index");
                }

                return View(_Auth_FormsActions);
            }
            catch (Exception ex)
            {
                return View(_Auth_FormsActions);
            }
        }

        public ActionResult Edit(int ActionID)
        {
            _BASEntities = new BASEntities();
            Auth_FormsActions Auth_FormsActions = _BASEntities.Auth_FormsActions.Where(x => x.ActionID == ActionID).FirstOrDefault();
            if (Auth_FormsActions == null)
            {
                return RedirectToAction("Index");
            }
            return View(Auth_FormsActions);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Auth_FormsActions _Auth_FormsActions, FormCollection form)
        {
            try
            {
                _BASEntities = new BASEntities();
                if (ModelState.IsValid)
                {
                    Auth_FormsActions Auth_FormsActions_Edit = _BASEntities.Auth_FormsActions.Where(x => x.ActionID == _Auth_FormsActions.ActionID).FirstOrDefault();
                    if (Auth_FormsActions_Edit == null)
                    {
                        return RedirectToAction("Index");
                    }
                    Auth_FormsActions_Edit.Name = _Auth_FormsActions.Name;
                    Auth_FormsActions_Edit.Icon = _Auth_FormsActions.Icon;
                    Auth_FormsActions_Edit.FlagActive = _Auth_FormsActions.FlagActive;

                    _BASEntities.SaveChanges();

                    return RedirectToAction("Index");
                }

                return View(_Auth_FormsActions);
            }
            catch (Exception ex)
            {
                return View(_Auth_FormsActions);
            }
        }

        public List<Auth_FormsActions> GetAllAuth_FormsActions()
        {
            _BASEntities = new BASEntities();
            List<Auth_FormsActions> Results = _BASEntities.Auth_FormsActions.ToList();

            return Results;
        }

    }
}

Fitosanidad/Views/Auth_FormsActions/Create.cshtml
@model Planner.Model.Auth_FormsActions

@using Resources;
@using Planner.Model;

@{
    ViewBag.Title = Resources.AccionesDisponiblesEnFormularios + " - " + Resources.Adicionar;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Auth_FormsActions/Create.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.VolverALaLista">
        <i class="fa fa-chevron-left"></i>
    </button>
    <button id="btnSave" name="btnSave" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Grabar">
        <i class="fa fa-save"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @using (Html.BeginForm("Create", "Auth_FormsActions", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "Create" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label for="PermissionID">@Resources.Id</label>
                    @Html.TextBoxFor(model => model.ActionID, null, new { @class = "form-control", @readonly = "readonly", @style = "Width: 100%; Max-Width: 100%" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Name">@Resources.Descripcion</label>
                    @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control", @style = "Width: 100%; Max-Width: 100%" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Icon">@Resources.Icono</label>
                    [ <i id="icoOptionIcon" name="icoOptionIcon" class="fa fa-image"></i> ]
                    <div class="input-group">
                        @Html.TextBoxFor(model => model.Icon, null, new { @class = "form-control", @style = "Width: 100%; Max-Width: 100%" })
                        <div class="input-group-btn">
                            <button class="btn btn-warning" type="button" onclick="GoToUrl('https://fontawesome.com/v4.7.0/icons/', true)">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label for="FlagActive">@Resources.Activo</label>
                    @Html.CheckBoxFor(model => model.FlagActive, new { @class = "checkbox" })
                </div>
            }
        </div>
    </div>
</div>

Fitosanidad/Views/Auth_FormsActions/Edit.cshtml
@model Planner.Model.Auth_FormsActions

@using Resources;
@using Planner.Model;

@{
    ViewBag.Title = Resources.AccionesDisponiblesEnFormularios + " - " + Resources.Editar;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Auth_FormsActions/Edit.js"></script>

<div class="btn-group">
    <button id="btnHome" name="btnHome" class="btn btn-warning waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.VolverALaLista">
        <i class="fa fa-chevron-left"></i>
    </button>
    <button id="btnSave" name="btnSave" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Grabar">
        <i class="fa fa-save"></i>
    </button>
</div>
<div class="Planner_Separator">
</div>

<div class="box box-success">
    <div class="box-body">
        <div class="col-xs-12 col-sm-12 col-md-12">
            @using (Html.BeginForm("Edit", "Auth_FormsActions", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "Edit" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label for="PermissionID">@Resources.Id</label>
                    @Html.TextBoxFor(model => model.ActionID, null, new { @class = "form-control", @readonly = "readonly", @style = "Width: 100%; Max-Width: 100%" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Name">@Resources.Descripcion</label>
                    @Html.TextBoxFor(model => model.Name, null, new { @class = "form-control", @style = "Width: 100%; Max-Width: 100%" })
                </div>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <label for="Icon">@Resources.Icono</label>
                    [ <i id="icoOptionIcon" name="icoOptionIcon" class="fa fa-image"></i> ]
                    <div class="input-group">
                        @Html.TextBoxFor(model => model.Icon, null, new { @class = "form-control", @style = "Width: 100%; Max-Width: 100%" })
                        <div class="input-group-btn">
                            <button class="btn btn-warning" type="button" onclick="GoToUrl('https://fontawesome.com/v4.7.0/icons/', true)">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label for="FlagActive">@Resources.Activo</label>
                    @Html.CheckBoxFor(model => model.FlagActive, new { @class = "checkbox" })
                </div>
            }
        </div>
    </div>
</div>

Fitosanidad/Views/Auth_FormsActions/Index.cshtml
@using Resources;

@{
    ViewBag.Title = Resources.AccionesDisponiblesEnFormularios;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Auth_FormsActions/Auth_FormsActions.js"></script>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="btn-group">
        <button id="btnCreate" name="btnCreate" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="@Resources.Adicionar">
            <i class="fa fa-plus"></i>
        </button>
    </div>
</div>
<div class="Planner_Separator">
</div>

<div class="col-xs-12 col-sm-12 col-md-12">
    <div class="box box-success">
        <div class="box-body">
            <div id="Auth_FormsActionsDataTable" class="form-group">
                <div id="resultsAuth_FormsActions">
                    <table id="tableAuth_FormsActions" class="table table-bordered table-striped table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>@Resources.Id</th>
                                <th>@Resources.Descripcion</th>
                                <th>@Resources.Icono</th>
                                <th>@Resources.Activo</th>
                                <th>@Resources.Acciones</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>